### ISSUE TITLE
Create a List of Most popular OSS Projects and Organisations

### ISSUE THREAD

**Issue by GeekyShiva** [github/open-source-guide#278]
I recommend and if people like this idea , we can work on adding a list of Open Source organizations and most Popular projects in various domains .

this will be a categorized list which will cater the beginner Open Source contributor audience and help them to give a start on the topic and project of their choice.

Ideas, discussion and healthy criticism ......... Welcomed :)

**Comment by etewiah** [comment]
Great idea.  I for one have struggled with getting exposure for my open source project!

**Comment by lutzhorn** [comment]
Which 'various domains' do you have in mind?

@etewiah How would such a list increase the exposure of *your* project?

**Comment by bkeepers** [comment]
Great suggestion, @GeekyShiva! Our team at GitHub has been thinking a bit about how to highlight projects, specifically ones that are good for new contributors.

I worry that trying to maintain a comprehensive list of projects will be a futile endeavor. The guides cover _examples_ of best practices, but don't aim to include comprehensive lists. Instead of including that content in the guides, I'd prefer to use GitHub [showcases](https://github.com/showcases) or [topics](https://github.com/blog/2309-introducing-topics).

For example, we maintain a showcase called [Great for new contributors](https://github.com/showcases/great-for-new-contributors). We're also planning to improve on sites like [Up For Grabs](http://up-for-grabs.net/#/) to help new contributors find a project to work on.
