### ISSUE TITLE
A Guide To Opensource DevRel

### ISSUE THREAD

**Issue by TheLarkInn** [github/open-source-guide#279]
I'm hoping to author some standalone content that will give the complete guide to Communication, Marketing, Developer Evangelism, and Developer Relations for an Open Source project. 

I would also love to add this content here. How does everyone else feel about this? I hate providing this link because it is about myself and webpack, but I think [sharing success stories like this](https://hackernoon.com/how-webpack-raised-15-000-in-3-months-and-the-future-of-open-source-cb2c9f68fffa) are important for people to understand why Communication and DevRel is so important.

**Comment by bkeepers** [comment]
Hey @TheLarkInn. I think adding more content about specific DevRel activities would be great! Specifically, updating [finding users](https://opensource.guide/finding-users/) guide, or it might even make sense to have a guide just on branding.

Since DevRel is a buzzword that will fall out of fashion at some point (see DevOps), I'd prefer to avoid using it in the guides. Feel free to open issues for specific DevRel topics and we can brainstorm how to cover them.

**Comment by nayafia** [comment]
:thumbsup: Adding a section on evangelism in the Finding Users guide (especially ongoing efforts, not just initial spreading the word) would be particularly useful. Please do it!

**Comment by TheLarkInn** [comment]
Absolutely. I plan to :-D
